<div class="container" data-mage-init='{"Dump/filter.js": {"keySearch": "#keySearch", "table": ".table"}}'>
    <!-- <h1><?= $block->escapeHtml(__('Configuration Dump')) ?></h1> -->


    <form id="keySearchForm">
        <label for="keySearch">Search by key:</label>
        <input type="text" id="keySearch" name="keySearch" oninput="filterModules()">
    </form>

    <table class="table">
        <thead>
            <tr>
                <th style="width: 20%;">Parent</th>
                <th style="width: 40%;">Key</th>
                <th style="width: 20%;">Value</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($block->getToggleableConfig() as $configItem): ?>
                <tr>
                    <td><?= $block->escapeHtml($configItem['parent']) ?></td>
                    <td><?= $block->escapeHtml($configItem['key']) ?></td>
                    <td><?= $block->escapeHtml($configItem['value']) ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<script>
    function filterModules() {
        var input, filter, table, tr, td, i, key;
        input = document.getElementById("keySearch");
        filter = input.value.toUpperCase();
        table = document.querySelector(".table");
        tr = table.getElementsByTagName("tr");

        for (i = 0; i < tr.length; i++) {
            key = tr[i].getElementsByTagName("td")[1]; 
            if (key) {
                keyText = key.textContent || key.innerText;
                if (keyText.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
</script>


